Add mkcd function

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -73,6 +73,14 @@ alias -g LL="2>&1 |less"
 
 autoload -Uz compinit && compinit
 
+mkcd() {
+    if (($# != 1)); then
+        echo 'Provide name of directory(/chain) as the only argument.'
+    else
+        mkdir -p "$1" && cd "$1" || echo "Couldn't create directory."
+    fi
+}
+
 # chezmoi init --apply https://github.com/CmdQ/dotfiles.git
 command -v chezmoi >/dev/null && eval "$(chezmoi completion zsh)"
 
